name: discord message
on: [push]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    outputs:
      isolated_tests_status: ${{ steps.test1.outputs.exit_code }}
      contract_tests_status: ${{ steps.test2.outputs.exit_code }}
    steps:
      - name: Test1
        id: test1
        run: |
          echo "exit_code=1" >> "$GITHUB_OUTPUT"
          exit 0

      - name: Test2
        id: test2
        run: | 
          echo "exit_code=0" >> "$GITHUB_OUTPUT"
          exit 1
        
  notify:
    runs-on: ubuntu-latest
    needs: test
    if: failure()

    steps:
      - name: build message
        run: |
          if [ "${{needs.test.outputs.isolated_tests_status}}" -gt 0 ]; then
             echo "ISOLATED_TESTS_STRING=Isolated tests failed" >> $GITHUB_ENV
             echo "Failed"
          else
             echo "ISOLATED_TESTS_STRING=Isolated test passed" >> $GITHUB_ENV
             echo "Pass"
          fi

          if [ "${{needs.test.outputs.contract_tests_status}}" -gt 0 ]; then
             echo "CONTRACT_TESTS_STRING=Contract tests failed" >> $GITHUB_ENV
             echo "Failed"
          else
             echo "CONTRACT_TESTS_STRING=Contract tests passed" >> $GITHUB_ENV
             echo "Pass"
          fi:

      - name: Send discord notification
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          content: "Backend is broken :( @Engineering 💻"
          title: "backend tests"
          description: "${{env.ISOLATED_TESTS_STRING}}\n${{env.CONTRACT_TESTS_STRING}}"
          status: ${{needs.test.result}} 
          color: 0xff2a2a
          url: "https://github.com/joaodiogo10/testDiscordWebhook"
