name: discord message
on: [push]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    outputs:
      isolated_tests_status: ${{ steps.test1.outputs.exit_code }}
      contract_tests_status: ${{ steps.test2.outputs.exit_code }}
    steps:
      - name: Test1
        id: test1
        run: |
          echo "exit_code=1" >> "$GITHUB_OUTPUT"
          exit 0

      - name: Test2
        id: test2
        run: |
          echo "exit_code=0" >> "$GITHUB_OUTPUT"
          exit 1

  notify:
    runs-on: ubuntu-latest
    needs: test
    if: failure()

    steps:
      - name: build message
        run: |
          echo "isolated tests status code: ${{needs.test.outputs.isolated_tests_status}}"
          echo "contract tests status code: ${{needs.test.outputs.contract_tests_status}}"

          set_status_string() {
            local status=$1
            local env_name=$2
            local title=$3

            if [ -z "$status" ]; then
              echo "${env_name}=${title}: Skip" >> $GITHUB_ENV
            elif [ "$status" != "0" ]; then
              echo "${env_name}=${title}: Fail" >> $GITHUB_ENV
            else
              echo "${env_name}=${title}: Pass" >> $GITHUB_ENV
            fi
          }

          set_status_string "${{needs.test.outputs.isolated_tests_status}}" "ISOLATED_TESTS_RESULT" "Isolated tests"
          set_status_string "${{needs.test.outputs.contract_tests_status}}" "CONTRACT_TESTS_RESULT" "Contract tests"

      - name: Send discord notification
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          content: "Backend is broken :( <@Engineering>"
          title: "backend tests"
          description: |
            ${{env.ISOLATED_TESTS_RESULT}}
            ${{env.CONTRACT_TESTS_RESULT}}
          status: ${{needs.test.result}}
          color: 0xff2a2a
          url: "https://github.com/joaodiogo10/testDiscordWebhook"
