name: discord message
on: [push]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    outputs:
      test1_status: ${{ steps.test1.outputs.exit_code }}
      test2_status: ${{ steps.test2.outputs.exit_code }}
    steps:
      - name: Test1
        id: test1
        run: exit 1 >> $GITHUB_OUTPUT

      - name: Test2
        id: test
        run: exit 0 >> $GITHUB_OUTPUT
        
  notify:
    name: Notify
    runs-on: ubuntu-latest
    needs: test
    if: always()
    steps:
      - name: Send discord notification
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          content: "Hey <@everyone>"
          title: "backend tests"
          description: "Backend test ${{ needs.test.outputs.test1_status }} and ${{ needs.test.outputs.test2_status }}" 
          color: 0xff2a2a
          image: ${{ secrets.EMBED_IMAGE }}
          url: "https://github.com/joaodiogo10/testDiscordWebhook/actions/workflows/send_discord_notification.yaml"
