name: discord message
on: [push]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    outputs:
      isolated_tests_status: ${{ steps.test1.outputs.exit_code }}
      contract_tests_status: ${{ steps.test2.outputs.exit_code }}
    steps:
      - name: Test1
        id: test1
        run: exit 1

      - name: Test2
        id: test2
        run: exit 0

      - name: "Verify results"
        if: always()
        run: |
          echo "${{ steps.test1.outcome }}"
          echo "${{ steps.test2.outcome }}"

      - name: Send discord notification
        if: failure()
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          content: "Backend is broken :( <@Engineering>"
          title: "backend tests"
          description: |
            Isolated tests: ${${{steps.test1.outcome}} || "Skipped"}}
            Contract tests: ${${{steps.test2.outcome}} || "Skipped"}}
          status: ${{job.status}}
          color: 0xff2a2a
          url: "https://github.com/joaodiogo10/testDiscordWebhook"
