name: discord message
on: [push]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    outputs:
      test1_status: ${{ steps.test1.outputs.exit_code }}
      test2_status: ${{ steps.test2.outputs.exit_code }}
    steps:
      - name: Test1
        id: test1
        run: echo "exit_code=world" >> "$GITHUB_OUTPUT"

      - name: Test2
        id: test2
        run: echo "exit_code=world" >> "$GITHUB_OUTPUT"
        
  notify:
    name: Notify
    runs-on: ubuntu-latest
    needs: test
    if: always()
    steps:
      - name: echo
        run: |
          MY_STRING=$(cat << EOF
          first line
          second line
          third line
          EOF
          )
        #echo ${{ needs.test.outputs.test1_status }} ${{ needs.test.outputs.test2_status }}
        
      - name: Send discord notification
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          content: "Hey <@everyone>"
          title: "backend tests"
          description: "${{ env.MY_STRING }}" 
          color: 0xff2a2a
          image: ${{ secrets.EMBED_IMAGE }}
          url: "https://github.com/joaodiogo10/testDiscordWebhook/actions/workflows/send_discord_notification.yaml"
        
