name: discord message
on: [push]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    outputs:
      test1_status: ${{ steps.test1.outputs.exit_code }}
      test2_status: ${{ steps.test2.outputs.exit_code }}
    steps:
      - name: Test1
        id: test1
        run: echo "exit_code=world" >> "$GITHUB_OUTPUT"

      - name: Test2
        id: test2
        run: echo "exit_code=world" >> "$GITHUB_OUTPUT"
        
  notify:
    name: Notify
    runs-on: ubuntu-latest
    needs: test
    if: always()
    steps:
      - name: build string
        run: |
          MULTI_LINES_TEXT="this is line one \n
                            this is line two \n
                            this is line three \n"    

          echo "MULTI_LINES_TEXT_ENV_VAR<<EOF" >> $GITHUB_ENV
          # here we can place the command that will generate multi-line text
          echo $MULTI_LINES_TEXT >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: echo
        run: echo ${{ env.MULTI_LINES_TEXT_ENV_VAR }}
        
      - name: Send discord notification
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          content: "Hey <@everyone>"
          title: "backend tests"
          description: "${{ env.MY_STRING }}" 
          color: 0xff2a2a
          image: ${{ secrets.EMBED_IMAGE }}
          url: "https://github.com/joaodiogo10/testDiscordWebhook/actions/workflows/send_discord_notification.yaml"
        
