name: discord message
on: [push]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    outputs:
      isolated_tests_status: ${{ steps.test1.outputs.exit_code }}
      contract_tests_status: ${{ steps.test2.outputs.exit_code }}
    steps:
      - name: Test1
        id: test1
        run: |
          echo "exit_code=1" >> "$GITHUB_OUTPUT"
          exit 0

      - name: Test2
        id: test2
        run: |
          echo "exit_code=0" >> "$GITHUB_OUTPUT"
          exit 1

  notify:
    runs-on: ubuntu-latest
    needs: test
    if: failure()

    steps:
      - name: build message
        run: |
          echo "isolated tests status code: ${{needs.test.outputs.isolated_tests_status}}"
          echo "contract tests status code: ${{needs.test.outputs.contract_tests_status}}"

          set_status_string() {
            local status=$1
            local name=$2
            local success_message=$3
            local failure_message=$4
            local skipped_message=$5

            if [ -z "$status" ]; then
              echo "${name}=${skipped_message}" >> $GITHUB_ENV
            elif [ "$status" != "0" ]; then
              echo "${name}=${failure_message}" >> $GITHUB_ENV
            else
              echo "${name}=${success_message}" >> $GITHUB_ENV
            fi
          }

          set_status_string "${{needs.test.outputs.isolated_tests_status}}" "ISOLATED_TESTS_STRING" "Isolated tests passed" "Isolated tests failed" "Isolated tests skipped"
          set_status_string "${{needs.test.outputs.contract_tests_status}}" "CONTRACT_TESTS_STRING" "Contract tests passed" "Contract tests failed" "Contract test skipped"

      - name: Send discord notification
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          content: "Backend is broken :( <@Engineering>"
          title: "backend tests"
          description: "${{env.ISOLATED_TESTS_STRING}}\n${{env.CONTRACT_TESTS_STRING}}"
          status: ${{needs.test.result}}
          color: 0xff2a2a
          url: "https://github.com/joaodiogo10/testDiscordWebhook"
